/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Service.IChiTietSanPhamService;
import Service.IIMService;
import Service.IKhachHangService;
import Service.IVoucherService;
import Service.QLHoaDonService;
import Service.impl.ChiTietHoaDonServiceImpl;
import Service.impl.ChiTietSanPhamService;
import Service.impl.IMService;
import Service.impl.KhachHangImpl;
import Service.impl.QLHoaDonImpl;
import Service.impl.VoucherImpl;
import Service.lChiTietHoaDonService;
import ViewModel.QLChiTietHoaDon;
import ViewModel.QLHoaDonViewModel;
import ViewModel.QLVoucher;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hieucode
 */
public class BaoCao_ChiTietHD extends javax.swing.JFrame {

    public String idHd;

    public void setIdHd(String idHd) {
        this.idHd = idHd;
    }

    private lChiTietHoaDonService chiTietHoaDonService = new ChiTietHoaDonServiceImpl();
    private IKhachHangService khachHangSe = new KhachHangImpl();
    private IVoucherService voucherSE = new VoucherImpl();
    private List<QLChiTietHoaDon> lstIdHoaDon = new ArrayList<>();
    private QLHoaDonService iHoaDonService = new QLHoaDonImpl();
    private IChiTietSanPhamService iCTSPService = new ChiTietSanPhamService();
    private IIMService iIMSe = new IMService();
    private int viTri = 0;
    private DefaultComboBoxModel comboBox = new DefaultComboBoxModel();

    /**
     * Creates new form QLSanPhamFrame
     */
    public BaoCao_ChiTietHD(String id) {
        initComponents();
        setLocationRelativeTo(null);
        loadData(id);
        idHd = id;
        txtTongTien.setRequestFocusEnabled(false);
        QLHoaDonViewModel qlhdvm = iHoaDonService.getHDByID(id);
        txtSDTKH.setText(chiTietHoaDonService.getSDTKHByID(qlhdvm.getTenKhachHang()));
        txtTenKH.setText(chiTietHoaDonService.getByTenKhachHang(qlhdvm.getTenKhachHang()));
        String loaiHinhTT = "";
        txtLoaiHinhThanhToanBC.setText(qlhdvm.getLoaiHinhThanhToan());
        txtTienOnlineBC.setText(qlhdvm.getTienOnline() + "");
        txtTienMatBC.setText(qlhdvm.getTienMat() + "");

        txtTongTien.setText(qlhdvm.getTongtien() + "");
        txtTongTienSauGiam.setText(qlhdvm.getTongtTenSauGiam() + "");
        ArrayList<QLVoucher> qlvs = voucherSE.getAllVoucherTrangThai0();
        for (QLVoucher qlv : qlvs) {
            if (qlv.getId().equals(qlhdvm.getTenVoucher())) {
                qlhdvm.setTenVoucher(qlv.getTen());
                txtVoucher.setText(qlv.getTen());
            }
        }
    }

    public void loadData(String id) {
        DefaultTableModel model = (DefaultTableModel) tblBang.getModel();
        model.setRowCount(0);
        int count = 1;
        ArrayList<QLChiTietHoaDon> list = this.chiTietHoaDonService.getAllTrangThai1(id);
        BigDecimal columnSum = BigDecimal.ZERO;
        for (QLChiTietHoaDon item : list) {
            columnSum = columnSum.add(item.getDonGia());
        }
        txtTongTien.setText(columnSum.toString());
        for (QLChiTietHoaDon qlct : list) {
            model.addRow(new Object[]{
                count++,
                this.chiTietHoaDonService.getTenByIdLoaiSP(qlct.getIdLoaiSP()),
                this.chiTietHoaDonService.getTenByIdBoNho(qlct.getIdBoNho()),
                this.chiTietHoaDonService.getTenByIdManHnh(qlct.getIdManHinh()),
                this.chiTietHoaDonService.getTenByIdCamera(qlct.getIdCamera()),
                this.chiTietHoaDonService.getTenByIdMauSac(qlct.getIdMauSac()),
                this.chiTietHoaDonService.getTenByIdPin(qlct.getIdPin()),
                qlct.getIM(),
                qlct.getDonGia(),
                qlct.getSoLuong(),
                qlct.getThanhTien()

            });

        }
    }

    public void clearForm() {
//        txtDiaChi.setText("--");
//        txtNguoiNhan.setText("--");
//        txtSDT.setText("--");
//        txtLyDoSua.setText("--");
    }

    BigDecimal sum = BigDecimal.ZERO;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        txtSDTKH = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();
        txtVoucher = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtTongTienSauGiam = new javax.swing.JTextField();
        txtLoaiHinhThanhToanBC = new javax.swing.JTextField();
        txtTienOnlineBC = new javax.swing.JTextField();
        txtTienMatBC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi tiết hóa đơn");

        jPanel2.setBackground(new java.awt.Color(24, 154, 180));
        jPanel2.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel41.setText("SĐT KH:");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(90, 240, 60, 30);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setText("Loại hình thanh toán");
        jPanel2.add(jLabel42);
        jLabel42.setBounds(90, 290, 140, 30);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setText("Tiền mặt:");
        jPanel2.add(jLabel44);
        jLabel44.setBounds(90, 350, 110, 30);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setText("Tiền online");
        jPanel2.add(jLabel45);
        jLabel45.setBounds(90, 400, 80, 30);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setText("Tổng tiền:");
        jPanel2.add(jLabel43);
        jLabel43.setBounds(530, 200, 70, 30);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setText("Voucher:");
        jPanel2.add(jLabel47);
        jLabel47.setBounds(530, 240, 100, 30);

        txtTongTien.setRequestFocusEnabled(false);
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });
        jPanel2.add(txtTongTien);
        txtTongTien.setBounds(680, 200, 150, 30);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel48.setText("Tổng tiền sau giảm:");
        jPanel2.add(jLabel48);
        jLabel48.setBounds(530, 290, 140, 30);

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Bộ nhớ", "Màn hình", "Camera", "Màu sắc", "Pin", "IMEI", "Đơn giá", "SL", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBang);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(50, 50, 910, 130);

        txtSDTKH.setRequestFocusEnabled(false);
        txtSDTKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSDTKHMousePressed(evt);
            }
        });
        txtSDTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTKHActionPerformed(evt);
            }
        });
        jPanel2.add(txtSDTKH);
        txtSDTKH.setBounds(220, 240, 160, 30);

        btnQuayLai.setBackground(new java.awt.Color(24, 154, 180));
        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/back (2) (1).png"))); // NOI18N
        btnQuayLai.setBorder(null);
        btnQuayLai.setBorderPainted(false);
        btnQuayLai.setContentAreaFilled(false);
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuayLai);
        btnQuayLai.setBounds(10, 10, 30, 20);

        txtVoucher.setRequestFocusEnabled(false);
        txtVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoucherActionPerformed(evt);
            }
        });
        jPanel2.add(txtVoucher);
        txtVoucher.setBounds(680, 240, 150, 30);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setText("Tên KH:");
        jPanel2.add(jLabel49);
        jLabel49.setBounds(90, 200, 60, 30);

        txtTenKH.setRequestFocusEnabled(false);
        txtTenKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTenKHMousePressed(evt);
            }
        });
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });
        jPanel2.add(txtTenKH);
        txtTenKH.setBounds(220, 200, 160, 30);

        txtTongTienSauGiam.setRequestFocusEnabled(false);
        txtTongTienSauGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienSauGiamActionPerformed(evt);
            }
        });
        jPanel2.add(txtTongTienSauGiam);
        txtTongTienSauGiam.setBounds(680, 290, 150, 30);

        txtLoaiHinhThanhToanBC.setRequestFocusEnabled(false);
        txtLoaiHinhThanhToanBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLoaiHinhThanhToanBCMousePressed(evt);
            }
        });
        txtLoaiHinhThanhToanBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiHinhThanhToanBCActionPerformed(evt);
            }
        });
        jPanel2.add(txtLoaiHinhThanhToanBC);
        txtLoaiHinhThanhToanBC.setBounds(240, 290, 160, 30);
        jPanel2.add(txtTienOnlineBC);
        txtTienOnlineBC.setBounds(210, 400, 160, 30);
        jPanel2.add(txtTienMatBC);
        txtTienMatBC.setBounds(210, 350, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTKHActionPerformed

    }//GEN-LAST:event_txtSDTKHActionPerformed

    private void txtSDTKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTKHMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTKHMousePressed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked

    }//GEN-LAST:event_tblBangMouseClicked

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoucherActionPerformed

    private void txtTenKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenKHMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHMousePressed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void txtTongTienSauGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienSauGiamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienSauGiamActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void txtLoaiHinhThanhToanBCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoaiHinhThanhToanBCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiHinhThanhToanBCMousePressed

    private void txtLoaiHinhThanhToanBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiHinhThanhToanBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiHinhThanhToanBCActionPerformed

    private BaoCao_ChiTietHD() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCao_ChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCao_ChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCao_ChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCao_ChiTietHD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCao_ChiTietHD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtLoaiHinhThanhToanBC;
    private javax.swing.JTextField txtSDTKH;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienMatBC;
    private javax.swing.JTextField txtTienOnlineBC;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTongTienSauGiam;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables
}
