/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Utility.Uhelper;
import Service.IKhachHangService;
import Service.IVoucherService;
import Service.impl.KhachHangImpl;
import Service.impl.VoucherImpl;
import ViewModel.QLKhachHang;
import ViewModel.QLVoucher;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QLKhachHang_ChiTietHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form QLKhachHang_ChiTietHoaDon
     */
    private IVoucherService voucherSe = new VoucherImpl();
    private IKhachHangService khachHangSe = new KhachHangImpl();
    private DefaultTableModel model = new DefaultTableModel();
    private DefaultComboBoxModel comboBox = new DefaultComboBoxModel();
    ArrayList<QLKhachHang> _listTimKiem;
    QLVoucher _qlVoucher;
    int index;

    public QLKhachHang_ChiTietHoaDon() {

        initComponents();
        setLocationRelativeTo(null);

        loadData(khachHangSe.getAllKhachHangTrangThai0());
    }

    private void loadData(ArrayList<QLKhachHang> listQLKH) {

        model.setRowCount(0);
        model = (DefaultTableModel) tblQLKhachHang.getModel();
        for (int i = 0; i < listQLKH.size(); i++) {
            model.addRow(new Object[]{
                i + 1,
                listQLKH.get(i).getTen(),
                listQLKH.get(i).getDiaChi(),
                listQLKH.get(i).getSdt()
            });
        }
    }

    private void showDetail() {

        QLKhachHang qLKhachHang = khachHangSe.getAllKhachHangTrangThai0().get(index);
        txtTenKH.setText(qLKhachHang.getTen());
        txtDiaChi.setText(qLKhachHang.getDiaChi());
        txtSdt.setText(qLKhachHang.getSdt());
        tblQLKhachHang.setRowSelectionInterval(index, index);

    }

    private void clearForm() {

        txtTenKH.setText("");
        txtDiaChi.setText("");
        txtSdt.setText("");
        tblQLKhachHang.clearSelection();
        index = -1;
    }

    private QLKhachHang getFormKhachHang() {

        String ten = txtTenKH.getText();
        String diaChi = txtDiaChi.getText();
        String sdt = txtSdt.getText();
        QLKhachHang qlkh = new QLKhachHang(ten, diaChi, sdt);
        return qlkh;
    }

    private Boolean validateForm() {

        if (Uhelper.checkNull(txtTenKH, "Nhập tên khách hàng")) {
            return true;
        }
        if (Uhelper.checkNull(txtDiaChi, "Nhập địa chỉ")) {
            return true;
        }
        if (Uhelper.checkNull(txtSdt, "Nhập SĐT")) {
            return true;
        }
        if (Uhelper.checkSDT(txtSdt, "Nhập SĐT là số và đủ 10 số")) {
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThanhToan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLKhachHang = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThanhToan.setBackground(new java.awt.Color(24, 154, 180));
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });
        btnThanhToan.setLayout(null);

        tblQLKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên khách hàng", "Địa chỉ", "SĐT"
            }
        ));
        tblQLKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLKhachHang);

        btnThanhToan.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 570, 180);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Tên KH:");
        btnThanhToan.add(jLabel10);
        jLabel10.setBounds(70, 270, 70, 22);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("Địa chỉ:");
        btnThanhToan.add(jLabel18);
        jLabel18.setBounds(70, 310, 110, 22);
        btnThanhToan.add(jLabel19);
        jLabel19.setBounds(20, 390, 100, 120);
        btnThanhToan.add(txtTenKH);
        txtTenKH.setBounds(190, 270, 180, 30);
        btnThanhToan.add(txtDiaChi);
        txtDiaChi.setBounds(190, 310, 180, 30);
        btnThanhToan.add(txtSdt);
        txtSdt.setBounds(190, 350, 180, 30);

        jButton3.setBackground(new java.awt.Color(24, 154, 180));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/back (2) (1).png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        btnThanhToan.add(jButton3);
        jButton3.setBounds(0, 0, 30, 30);

        btnAdd.setBackground(new java.awt.Color(24, 154, 180));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/add .png"))); // NOI18N
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnThanhToan.add(btnAdd);
        btnAdd.setBounds(440, 280, 31, 30);

        btnUpdate.setBackground(new java.awt.Color(24, 154, 180));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/edit .png"))); // NOI18N
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        btnThanhToan.add(btnUpdate);
        btnUpdate.setBounds(440, 330, 31, 30);

        btnClear.setBackground(new java.awt.Color(24, 154, 180));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/eraser 1.png"))); // NOI18N
        btnClear.setBorder(null);
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnThanhToan.add(btnClear);
        btnClear.setBounds(500, 280, 51, 30);

        btnDelete.setBackground(new java.awt.Color(24, 154, 180));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/delete .png"))); // NOI18N
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        btnThanhToan.add(btnDelete);
        btnDelete.setBounds(490, 330, 63, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("SĐT:");
        btnThanhToan.add(jLabel16);
        jLabel16.setBounds(70, 350, 70, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblQLKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLKhachHangMouseClicked

        index = tblQLKhachHang.getSelectedRow();
        showDetail();
    }//GEN-LAST:event_tblQLKhachHangMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (validateForm()) {
            return;
        }
        getFormKhachHang();
        QLKhachHang qlkh = khachHangSe.addKhachHang(getFormKhachHang());
        if (qlkh != null) {
            loadData(khachHangSe.getAllKhachHangTrangThai0());
            clearForm();
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        index = tblQLKhachHang.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng trước khi sửa");
            return;
        }
        QLKhachHang qlkh = khachHangSe.getAllKhachHangTrangThai0().get(index);
        String id = qlkh.getId();
        if (validateForm()) {
            return;
        }
        getFormKhachHang();
        qlkh = khachHangSe.updateKhachHang(getFormKhachHang(), id);
        if (qlkh != null) {
            loadData(khachHangSe.getAllKhachHangTrangThai0());
            clearForm();
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        index = tblQLKhachHang.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng trước khi xoá");
            return;
        }
        QLKhachHang qlkh = khachHangSe.getAllKhachHangTrangThai0().get(index);
        String id = qlkh.getId();

        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa khách hàng " + qlkh.getTen());
        if (hoi != JOptionPane.YES_NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Bạn đã không xóa");
            return;
        }

        qlkh = khachHangSe.deleteKhachHang(qlkh, id);
        if (qlkh != null) {
            loadData(khachHangSe.getAllKhachHangTrangThai0());
            clearForm();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked

    }//GEN-LAST:event_btnThanhToanMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang_ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang_ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang_ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKhachHang_ChiTietHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKhachHang_ChiTietHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel btnThanhToan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQLKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
