/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Utility.Uhelper;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class SendEmail extends javax.swing.JFrame {

    /**
     * Creates new form SendEmail
     */
    public SendEmail() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(24,154,180));
    }
    public static String RandomMaOTP() {
        String kiTu = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890";
        StringBuilder sb = new StringBuilder(6);
        Random random = new Random();

        for (int i = 0; i < 6; i++) {
            int index = random.nextInt(kiTu.length());
            char randomChar = kiTu.charAt(index);
            sb.append(randomChar);
        }
        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmailKhoiPhuc = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaOTP = new javax.swing.JTextField();
        btnKiemTra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nhập email khôi phục");

        btnSend.setText("Lấy mã");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel2.setText("Nhập mã OTP");

        btnKiemTra.setText("Kiểm Tra");
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnKiemTra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSend)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKiemTra, btnSend, jButton1});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEmailKhoiPhuc, txtMaOTP});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnSend))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKiemTra)
                    .addComponent(jButton1))
                .addGap(84, 84, 84))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKiemTra, btnSend, jButton1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmailKhoiPhuc, txtMaOTP});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
         if(Uhelper.checkNull(txtEmailKhoiPhuc, " Email không được để trống"))return;
          if(Uhelper.checkEmail(txtEmailKhoiPhuc, "Email phải đúng định dạng"))return;
          
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn lấy mã OTP không ?");

            if (hoi == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Bạn đã không lấy mã ");
                return;
            } 
            else if(hoi == JOptionPane.YES_OPTION){
        String toEmail = txtEmailKhoiPhuc.getText();
        String from = "cuahangdienthoai1102@gmail.com";
        String randomString = RandomMaOTP();
        try {
            String MaOTP = randomString ;
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("MaOTP.txt"));
            oos.writeObject(MaOTP);
            System.out.println(""+MaOTP);
            oos.flush();
            oos.close();          
        } catch (Exception e) {
            e.printStackTrace();
        }
        String FromEmailpassword = "vglhvfuopxosedcf";
        
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        
        Session session = Session.getDefaultInstance(props, new Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication(from,FromEmailpassword);
                }
        });
        try{
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
            message.setSubject("CỬA HÀNG ĐIỆN THOẠI");
            message.setText("Mã OTP của bạn là: "+randomString);
            Transport.send(message);
                   JOptionPane.showMessageDialog(this, "Lấy mã OTP thành công vui lòng kiểm tra email để xác nhận");
        }
        catch(Exception ex){
            System.out.println(ex);
        }
            }
    }//GEN-LAST:event_btnSendActionPerformed

      public void ghiEmail() {
        try {
            String Email = txtEmailKhoiPhuc.getText();
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Email.txt"));
            oos.writeObject(Email);
            System.out.println(""+Email);
            oos.flush();
            oos.close();          
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
      
//      public void docMaOTP(){
//          try{
//           String maOTP = txtMaOTP.getText(); 
//            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("MaOTP.txt"));
//           Object docMa = ois.readObject();
//              System.out.println(""+docMa);
//            ois.close();
//         
//          if (maOTP.equals(docMa)) {
//                new DoiMatKhau().setVisible(true);
//            } else {
//               JOptionPane.showMessageDialog(this,"Mã OTP chưa chính xác vui lòng kiểm tra lại");
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        
//        }
     private static int soLanNhapMaOTP = 5; 
    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        // TODO add your handling code here:
           if(Uhelper.checkNull(txtMaOTP, " Mã OTP không được để trống"))return;
        try{
           String maOTP = txtMaOTP.getText(); 
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("MaOTP.txt"));
            Object docMa = ois.readObject();
              System.out.println(""+docMa);
            ois.close();
         
          if (maOTP.equals(docMa)) {
              ghiEmail();
                new DoiMatKhau().setVisible(true);
            }

          else {
             {
                soLanNhapMaOTP--;
                if (soLanNhapMaOTP > 0) {
                    JOptionPane.showMessageDialog(this,"Mã OTP chưa chính xác bạn còn " + soLanNhapMaOTP +" lần nhập mã OTP");
                } else {
                    JOptionPane.showMessageDialog(this,"Bạn đã hết số lần nhập mã OPT , vui lòng quay lại sau ít phút");
                    btnKiemTra.setEnabled(false);
                }
            }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
         ghiEmail();
//        new SendEmail() .setVisible(false);
    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new LoginFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEmailKhoiPhuc;
    private javax.swing.JTextField txtMaOTP;
    // End of variables declaration//GEN-END:variables
}
